server:
  port: 9001
#  ban dau la doan nay
spring:
  application:
    name: DEPARTMENT-SERVICE

#thay bang
#spring:
#  application:
#    name: DEPARTMENT-SERVICE
#zipkin:
#  base-url: http://127.0.0.1:9411/